## Configuration for Eureka
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true # For local development. Set to false if you want to use the hostname in a DNS-enabled environment
    hostname: ${HOSTNAME:localhost}

## Configuration for App name and Spring Data
spring:
  application:
    name: ${APP_NAME:ms-users}
  datasource:
    url: jdbc:h2:mem:usersdb;Mode=MySQL
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

## Instance port
server:
  port: ${PORT:8083}

## Configuracion secundaria (custom)
getBookings:
  url: http://ms-bookings/bookings?hotelId=%s&startDate=%s&endDate=%s

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
